-- MySQL Script generated by MySQL Workbench
-- 01/17/17 18:05:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema techquo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema techquo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `techquo` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `techquo` ;

-- -----------------------------------------------------
-- Table `techquo`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techquo`.`user` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Fname` VARCHAR(40) NOT NULL,
  `Lname` VARCHAR(45) NOT NULL,
  `Q1` INT UNSIGNED NOT NULL,
  `A1` VARCHAR(45) NOT NULL,
  `Q2` INT UNSIGNED NOT NULL,
  `A2` VARCHAR(45) NULL,
  `Role` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Email` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `DOB` DATE NULL,
  `url` VARCHAR(60) NULL,
  `expiry` DATE NULL,
  `activity` TINYINT(1) NULL DEFAULT 0,
  `Registered` TINYINT(1) NULL DEFAULT 0,
  `Country` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `Profile_Picture` BLOB NULL,
  `Profile_views` INT UNSIGNED NULL DEFAULT 0,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techquo`.`Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techquo`.`Question` (
  `Ques_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NULL,
  `Question` VARCHAR(500) NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `count` INT NULL,
  PRIMARY KEY (`Ques_id`),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `techquo`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techquo`.`Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techquo`.`Tags` (
  `Ques_id` INT NOT NULL,
  `tag` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Ques_id`, `tag`),
  CONSTRAINT `Ques_id`
    FOREIGN KEY (`Ques_id`)
    REFERENCES `techquo`.`Question` (`Ques_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techquo`.`Answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techquo`.`Answer` (
  `Ans_id` INT NOT NULL AUTO_INCREMENT,
  `Ques_id` INT NOT NULL,
  `Answer` VARCHAR(1000) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_id` INT UNSIGNED NOT NULL,
  `upvotes` INT UNSIGNED NULL,
  `downvotes` INT UNSIGNED NULL,
  PRIMARY KEY (`Ans_id`),
  INDEX `Ques_id_idx` (`Ques_id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `Ques_id`
    FOREIGN KEY (`Ques_id`)
    REFERENCES `techquo`.`Question` (`Ques_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `techquo`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techquo`.`Interests_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techquo`.`Interests_user` (
  `user_id` INT UNSIGNED NOT NULL,
  `Interests` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`user_id`, `Interests`),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `techquo`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techquo`.`Education_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techquo`.`Education_user` (
  `user_id` INT UNSIGNED NOT NULL,
  `Education` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Education`),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `techquo`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
